spring.application.name=wallet-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wallet}
spring.datasource.username=${DB_USER:wallet}
spring.datasource.password=${DB_PASS:wallet}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

management.endpoints.web.exposure.include=health,prometheus,info
management.endpoint.health.show-details=always

spring.jackson.property-naming-strategy=SNAKE_CASE

logging.structured.format.console=logstash

server.port=${PORT:8080}
